# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='text',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
